In [47]:
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [27]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones([1,3])

array([[1., 1., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [39]:
np.random.rand(2, 3), np.random.randn(3, 3)

(array([[0.86889145, 0.94580808, 0.25584297],
        [0.31451974, 0.25019018, 0.62752659]]),
 array([[ 0.64212601, -1.91299395,  0.62068162],
        [ 1.83660751, -0.32906328,  1.53535883],
        [ 1.36216221, -0.5135325 , -1.10017567]]))

In [69]:
a=np.random.randint(0, 10, size=(3, 3))
a

array([[2, 7, 6],
       [8, 2, 5],
       [6, 7, 5]])

In [83]:
a1=np.random.randint(0, 10, size=(3, 3))
a1

array([[5, 7, 7],
       [4, 5, 0],
       [6, 0, 5]])

In [53]:
arr.shape

(3,)

In [79]:
a.reshape(3,3)

array([[2, 7, 6],
       [8, 2, 5],
       [6, 7, 5]])

In [63]:
arr.flatten()

array([1, 2, 3])

In [71]:
np.transpose(a)

array([[2, 8, 6],
       [7, 2, 7],
       [6, 5, 5]])

In [89]:
np.concatenate((a, a1), axis=0)

array([[2, 7, 6],
       [8, 2, 5],
       [6, 7, 5],
       [5, 7, 7],
       [4, 5, 0],
       [6, 0, 5]])

In [91]:
np.hstack((a, a1)), np.vstack((a, a1))

(array([[2, 7, 6, 5, 7, 7],
        [8, 2, 5, 4, 5, 0],
        [6, 7, 5, 6, 0, 5]]),
 array([[2, 7, 6],
        [8, 2, 5],
        [6, 7, 5],
        [5, 7, 7],
        [4, 5, 0],
        [6, 0, 5]]))

In [97]:
np.add(a,a1)

array([[ 7, 14, 13],
       [12,  7,  5],
       [12,  7, 10]])

In [101]:
np.subtract(a,a1)

array([[-3,  0, -1],
       [ 4, -3,  5],
       [ 0,  7,  0]])

In [103]:
np.multiply(a,a1)

array([[10, 49, 42],
       [32, 10,  0],
       [36,  0, 25]])

In [105]:
np.divide(a,a1)

C:\Users\Bhavana\AppData\Local\Temp\ipykernel_9176\2305498796.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,a1)


array([[0.4       , 1.        , 0.85714286],
       [2.        , 0.4       ,        inf],
       [1.        ,        inf, 1.        ]])

In [107]:
np.dot(a,a1)

array([[74, 49, 44],
       [78, 66, 81],
       [88, 77, 67]])

In [113]:
np.sqrt(a)

array([[1.41421356, 2.64575131, 2.44948974],
       [2.82842712, 1.41421356, 2.23606798],
       [2.44948974, 2.64575131, 2.23606798]])

In [115]:
np.log(a)

array([[0.69314718, 1.94591015, 1.79175947],
       [2.07944154, 0.69314718, 1.60943791],
       [1.79175947, 1.94591015, 1.60943791]])

In [117]:
np.exp(a)

array([[   7.3890561 , 1096.63315843,  403.42879349],
       [2980.95798704,    7.3890561 ,  148.4131591 ],
       [ 403.42879349, 1096.63315843,  148.4131591 ]])

In [121]:
np.power(a,2)

array([[ 4, 49, 36],
       [64,  4, 25],
       [36, 49, 25]], dtype=int32)

In [123]:
np.mean(a)

5.333333333333333

np.median(a)

In [126]:
np.std(a)

2.0

In [128]:
np.sum(a)

48

In [132]:
np.prod(a)

1411200

In [144]:
a[0]

array([2, 7, 6])

In [146]:
 a[1:3]

array([[8, 2, 5],
       [6, 7, 5]])

In [148]:
 a[:, 1]

array([7, 2, 7])

In [150]:
a

array([[2, 7, 6],
       [8, 2, 5],
       [6, 7, 5]])

In [154]:
a[a > 5]

array([7, 6, 8, 6, 7])

In [162]:
np.sort(a)

array([[2, 6, 7],
       [2, 5, 8],
       [5, 6, 7]])

In [164]:
np.argsort(a)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [166]:
np.where(a)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [168]:
np.unique(a)

array([2, 5, 6, 7, 8])

In [170]:
np.argmax(a)

5

In [172]:
np.argmin(a)

0

In [174]:
arr + 5

array([6, 7, 8])

In [176]:
np.linalg.inv(a)

array([[-3.33333333e-01,  1.33226763e-16,  3.33333333e-01],
       [ 6.66666667e-01, -5.38461538e-01, -5.12820513e-02],
       [-3.33333333e-01,  4.61538462e-01, -5.12820513e-02]])

In [178]:
np.linalg.eig(a)

EigResult(eigenvalues=array([16.34802701+0.j        , -1.1740135 +1.00364399j,
       -1.1740135 -1.00364399j]), eigenvectors=array([[ 0.54058318+0.j        ,  0.00695241-0.4259815j ,
         0.00695241+0.4259815j ],
       [ 0.5463015 +0.j        ,  0.69868959+0.j        ,
         0.69868959-0.j        ],
       [ 0.63978473+0.j        , -0.54095298+0.19414983j,
        -0.54095298-0.19414983j]]))

In [180]:
np.linalg.norm(a)

17.08800749063506

In [182]:
np.linalg.det(a)

38.99999999999999

In [186]:
np.linalg.solve(a,a1)

array([[ 0.33333333, -2.33333333, -0.66666667],
       [ 0.87179487,  1.97435897,  4.41025641],
       [-0.12820513, -0.02564103, -2.58974359]])

In [194]:
np.clip(arr, a_min=4, a_max=10)

array([4, 4, 4])

In [200]:
np.random.shuffle(arr)
arr

array([2, 3, 1])

In [204]:
np.save('data.npy', arr)
loaded = np.load('data.npy')
arr

array([2, 3, 1])

In [206]:
np.savetxt('data.txt', arr, delimiter=',')

In [208]:
arr

array([2, 3, 1])